[package]
name = "lean-multisig-py"
version = "0.1.0"
edition = "2021"

[lib]
name = "lean_multisig"
crate-type = ["cdylib"]

[features]
default = []
test_config = ["lean-multisig/test_config"]

[dependencies]
pyo3 = { version = "0.27", features = ["extension-module"] }
lean-multisig = { path = "../leanMultisig" }
ssz = { package = "ethereum_ssz", version = "0.10.0" }
