use backend::{precompute_dft_twiddles, KoalaBear};
use rec_aggregation::{
    init_aggregation_bytecode_from_dir, xmss_aggregate, xmss_verify_aggregation, AggregatedXMSS,
};
use leansig_wrapper::{
    xmss_public_key_from_ssz, xmss_signature_from_ssz, XmssPublicKey, XmssSignature,
    MESSAGE_LENGTH,
};

use pyo3::exceptions::PyValueError;
use pyo3::prelude::*;
use ssz::{Decode, DecodeError, Encode};

// Embedded .py files from rec_aggregation, generated by build.rs
include!(concat!(env!("OUT_DIR"), "/embedded_py.rs"));

/// Mode constant - "test" when compiled with test-config feature, "prod" otherwise.
#[cfg(feature = "test-config")]
pub const MODE: &str = "test";

#[cfg(not(feature = "test-config"))]
pub const MODE: &str = "prod";

/// SSZ container for the devnet4 aggregated XMSS proof.
///
/// This wraps the native `AggregatedXMSS` serialization (postcard + lz4)
/// as an opaque byte blob for the consensus layer.
///
/// SSZ layout (variable-length container):
///   offset(4 bytes) | proof_bytes(variable)
#[derive(Debug, Clone)]
pub struct Devnet4XmssAggregateSignature {
    /// Native serialized AggregatedXMSS (postcard + lz4 compressed).
    /// Contains pub_keys, proof, and bytecode_point (None encoded as absent).
    pub proof_bytes: Vec<u8>,
}

impl Encode for Devnet4XmssAggregateSignature {
    fn is_ssz_fixed_len() -> bool {
        false
    }

    fn ssz_bytes_len(&self) -> usize {
        self.proof_bytes.len()
    }

    fn ssz_append(&self, buf: &mut Vec<u8>) {
        buf.extend_from_slice(&self.proof_bytes);
    }
}

impl Decode for Devnet4XmssAggregateSignature {
    fn is_ssz_fixed_len() -> bool {
        false
    }

    fn from_ssz_bytes(bytes: &[u8]) -> Result<Self, DecodeError> {
        if bytes.is_empty() {
            return Err(DecodeError::InvalidByteLength {
                len: 0,
                expected: 1,
            });
        }

        Ok(Self {
            proof_bytes: bytes.to_vec(),
        })
    }
}

impl Devnet4XmssAggregateSignature {
    /// Create from a native AggregatedXMSS.
    pub fn from_aggregated(agg: &AggregatedXMSS) -> Self {
        Self {
            proof_bytes: agg.serialize(),
        }
    }

    /// Deserialize back to native AggregatedXMSS.
    pub fn to_aggregated(&self) -> Option<AggregatedXMSS> {
        AggregatedXMSS::deserialize(&self.proof_bytes)
    }
}

/// Extract embedded .py source files to a writable directory and return its path.
/// The lean compiler reads main.py (and its imports) from disk at runtime.
/// When the .so runs on a different machine than where it was built, the original
/// build-time path is not available, so we extract to a temp directory instead.
fn ensure_py_sources() -> &'static std::path::Path {
    use std::fs;
    use std::path::{Path, PathBuf};
    use std::sync::OnceLock;

    static SOURCE_DIR: OnceLock<PathBuf> = OnceLock::new();
    SOURCE_DIR.get_or_init(|| {
        // Try the original build-time path first (works on the build machine).
        let build_dir = Path::new(REC_AGGREGATION_MANIFEST_DIR);
        if build_dir.join("main.py").exists() {
            return build_dir.to_path_buf();
        }

    // Extract embedded files to a temp directory.
    let dir = std::env::temp_dir().join("lean_multisig_py_sources");
    fs::create_dir_all(&dir).unwrap_or_else(|e| {
        panic!("Failed to create temp directory '{}': {}", dir.display(), e)
    });
    for (name, content) in EMBEDDED_PY_FILES {
        let path = dir.join(name);
        fs::write(&path, content).unwrap_or_else(|e| {
            panic!("Failed to write embedded source '{}': {}", path.display(), e)
        });
    }
    dir
    })
}

/// Setup the prover for XMSS aggregation.
/// Call this once before first aggregation to avoid slowdown.
#[pyfunction]
fn setup_prover() {
    let dir = ensure_py_sources();
    init_aggregation_bytecode_from_dir(dir);
    precompute_dft_twiddles::<KoalaBear>(1 << 24);
}

/// Setup the verifier for XMSS aggregation.
/// Call this once before first verification to avoid slowdown.
#[pyfunction]
fn setup_verifier() {
    let dir = ensure_py_sources();
    init_aggregation_bytecode_from_dir(dir);
}

/// Aggregate XMSS signatures.
///
/// Args:
///     pub_keys_bytes: List of serialized public keys (each as bytes, SSZ format)
///     signatures_bytes: List of serialized signatures (each as bytes, SSZ format)
///     message_hash: 32-byte message hash
///     slot: Slot number (u32)
///     log_inv_rate: Inverse rate exponent for proof (1-4, lower = faster but bigger proofs)
///     children_bytes: Optional list of serialized AggregatedXMSS for hierarchical aggregation
///
/// Returns:
///     Serialized aggregated signature as bytes
///
/// Raises:
///     ValueError: If inputs are invalid or aggregation fails
#[pyfunction]
#[pyo3(signature = (pub_keys_bytes, signatures_bytes, message_hash, slot, log_inv_rate, children_bytes=None))]
fn aggregate_signatures(
    pub_keys_bytes: Vec<Vec<u8>>,
    signatures_bytes: Vec<Vec<u8>>,
    message_hash: Vec<u8>,
    slot: u32,
    log_inv_rate: usize,
    children_bytes: Option<Vec<(Vec<Vec<u8>>, Vec<u8>)>>,
) -> PyResult<(Vec<Vec<u8>>, Vec<u8>)> {
    // Validate message hash length
    if message_hash.len() != MESSAGE_LENGTH {
        return Err(PyValueError::new_err(format!(
            "message_hash must be exactly {} bytes, got {}",
            MESSAGE_LENGTH,
            message_hash.len()
        )));
    }

    // Validate that we have the same number of public keys and signatures
    if pub_keys_bytes.len() != signatures_bytes.len() {
        return Err(PyValueError::new_err(format!(
            "Number of public keys ({}) must match number of signatures ({})",
            pub_keys_bytes.len(),
            signatures_bytes.len()
        )));
    }

    // Deserialize public keys from SSZ
    let pub_keys: Vec<XmssPublicKey> = pub_keys_bytes
        .iter()
        .enumerate()
        .map(|(i, bytes)| {
            xmss_public_key_from_ssz(bytes)
                .map_err(|()| PyValueError::new_err(format!("Failed to deserialize public key {} (SSZ)", i)))
        })
        .collect::<PyResult<Vec<_>>>()?;

    // Deserialize signatures from SSZ
    let signatures: Vec<XmssSignature> = signatures_bytes
        .iter()
        .enumerate()
        .map(|(i, bytes)| {
            xmss_signature_from_ssz(bytes)
                .map_err(|()| PyValueError::new_err(format!("Failed to deserialize signature {} (SSZ)", i)))
        })
        .collect::<PyResult<Vec<_>>>()?;

    // Build raw_xmss pairs
    let raw_xmss: Vec<(XmssPublicKey, XmssSignature)> =
        pub_keys.into_iter().zip(signatures).collect();

    // Deserialize children if provided: each child is (pub_keys_ssz, agg_bytes)
    let children_parsed: Vec<(Vec<XmssPublicKey>, AggregatedXMSS)> = match children_bytes {
        Some(cb) => cb
            .iter()
            .enumerate()
            .map(|(i, (child_pks_bytes, child_agg_bytes))| {
                let child_pks: Vec<XmssPublicKey> = child_pks_bytes
                    .iter()
                    .enumerate()
                    .map(|(j, bytes)| {
                        xmss_public_key_from_ssz(bytes).map_err(|()| {
                            PyValueError::new_err(format!(
                                "Failed to deserialize child {} public key {} (SSZ)", i, j
                            ))
                        })
                    })
                    .collect::<PyResult<Vec<_>>>()?;
                let child_agg = AggregatedXMSS::deserialize(child_agg_bytes)
                    .ok_or_else(|| {
                        PyValueError::new_err(format!("Failed to deserialize child {} aggregation", i))
                    })?;
                Ok((child_pks, child_agg))
            })
            .collect::<PyResult<Vec<_>>>()?,
        None => vec![],
    };
    let children_with_keys: Vec<(&[XmssPublicKey], AggregatedXMSS)> = children_parsed
        .iter()
        .map(|(pks, agg)| (pks.as_slice(), agg.clone()))
        .collect();

    // Convert message_hash to array
    let message_array: [u8; MESSAGE_LENGTH] = message_hash
        .try_into()
        .map_err(|_| PyValueError::new_err("Failed to convert message_hash to fixed-size array"))?;

    // Call the aggregation function
    let (pub_keys_out, agg) = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        xmss_aggregate(&children_with_keys, raw_xmss, &message_array, slot, log_inv_rate)
    }))
    .map_err(|e| {
        let msg = if let Some(s) = e.downcast_ref::<&str>() {
            s.to_string()
        } else if let Some(s) = e.downcast_ref::<String>() {
            s.clone()
        } else {
            "unknown error".to_string()
        };
        PyValueError::new_err(format!("Aggregation failed: {}", msg))
    })?;

    // Serialize pub_keys using SSZ
    let pub_keys_ssz: Vec<Vec<u8>> = pub_keys_out
        .iter()
        .map(|pk| leansig_wrapper::xmss_public_key_to_ssz(pk))
        .collect();

    Ok((pub_keys_ssz, agg.serialize()))
}

/// Verify aggregated XMSS signatures.
///
/// Args:
///     message_hash: 32-byte message hash
///     agg_signature_bytes: Serialized aggregated signature as bytes
///     slot: Slot number (u32)
///
/// Returns:
///     None if verification succeeds
///
/// Raises:
///     ValueError: If inputs are invalid or verification fails
#[pyfunction]
fn verify_aggregated_signatures(
    pub_keys_bytes: Vec<Vec<u8>>,
    message_hash: Vec<u8>,
    agg_signature_bytes: Vec<u8>,
    slot: u32,
) -> PyResult<()> {
    // Validate message hash length
    if message_hash.len() != MESSAGE_LENGTH {
        return Err(PyValueError::new_err(format!(
            "message_hash must be exactly {} bytes, got {}",
            MESSAGE_LENGTH,
            message_hash.len()
        )));
    }

    // Deserialize public keys from SSZ
    let pub_keys: Vec<XmssPublicKey> = pub_keys_bytes
        .iter()
        .enumerate()
        .map(|(i, bytes)| {
            xmss_public_key_from_ssz(bytes)
                .map_err(|()| PyValueError::new_err(format!("Failed to deserialize public key {} (SSZ)", i)))
        })
        .collect::<PyResult<Vec<_>>>()?;

    // Convert message_hash to array
    let message_array: [u8; MESSAGE_LENGTH] = message_hash
        .try_into()
        .map_err(|_| PyValueError::new_err("Failed to convert message_hash to fixed-size array"))?;

    // Deserialize the aggregated signature
    let agg_sig = AggregatedXMSS::deserialize(&agg_signature_bytes)
        .ok_or_else(|| PyValueError::new_err("Failed to deserialize aggregated signature"))?;


    // Call the verification function
    xmss_verify_aggregation(pub_keys, &agg_sig, &message_array, slot)
        .map_err(|e| PyValueError::new_err(format!("Verification failed: {:?}", e)))?;

    Ok(())
}

/// SSZ-encode an aggregated signature (native bytes -> SSZ container).
///
/// Wraps the native serialized AggregatedXMSS as a Devnet4XmssAggregateSignature
/// SSZ container.
#[pyfunction]
fn ssz_encode_aggregate_signature(agg_signature_bytes: Vec<u8>) -> Vec<u8> {
    let container = Devnet4XmssAggregateSignature {
        proof_bytes: agg_signature_bytes,
    };
    container.as_ssz_bytes()
}

/// SSZ-decode an aggregated signature (SSZ container -> native bytes).
///
/// Decodes a Devnet4XmssAggregateSignature SSZ container back to native
/// serialized AggregatedXMSS bytes.
#[pyfunction]
fn ssz_decode_aggregate_signature(ssz_bytes: Vec<u8>) -> PyResult<Vec<u8>> {
    let container = Devnet4XmssAggregateSignature::from_ssz_bytes(&ssz_bytes)
        .map_err(|e| PyValueError::new_err(format!("SSZ decode failed: {:?}", e)))?;
    Ok(container.proof_bytes)
}

/// Get the mode this module was compiled with.
#[pyfunction]
fn get_mode() -> &'static str {
    MODE
}

fn register_functions(py_module: &Bound<'_, PyModule>) -> PyResult<()> {
    py_module.add("MODE", MODE)?;
    py_module.add_function(wrap_pyfunction!(setup_prover, py_module)?)?;
    py_module.add_function(wrap_pyfunction!(setup_verifier, py_module)?)?;
    py_module.add_function(wrap_pyfunction!(aggregate_signatures, py_module)?)?;
    py_module.add_function(wrap_pyfunction!(verify_aggregated_signatures, py_module)?)?;
    py_module.add_function(wrap_pyfunction!(ssz_encode_aggregate_signature, py_module)?)?;
    py_module.add_function(wrap_pyfunction!(ssz_decode_aggregate_signature, py_module)?)?;
    py_module.add_function(wrap_pyfunction!(get_mode, py_module)?)?;
    Ok(())
}

/// Python module for lean-multisig XMSS aggregation (test mode).
#[cfg(feature = "test-config")]
#[pymodule]
fn lean_multisig_test(py_module: &Bound<'_, PyModule>) -> PyResult<()> {
    register_functions(py_module)
}

/// Python module for lean-multisig XMSS aggregation (prod mode).
#[cfg(not(feature = "test-config"))]
#[pymodule]
fn lean_multisig(py_module: &Bound<'_, PyModule>) -> PyResult<()> {
    register_functions(py_module)
}
